[theme]
# Primary colors
primaryColor = "#1E3A8A"  # Deep academic blue
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8FAFC"
textColor = "#1E293B"
font = "Inter"

[server]
enableStaticServing = true

[browser]
gatherUsageStats = false
